all:
  hosts:
    trashscanner_server:
      ansible_host: "{{ server_host }}"
      ansible_user: "{{ server_user }}"
      ansible_ssh_private_key_file: "~/.ssh/deploy_key"
      ansible_python_interpreter: /usr/bin/python3
